#!/bin/bash
ls -Ap | awk 'BEGIN{ORS=","} {if ($0 == "./" || $0 == "../") print; else print $0} END{print "\n"}' | awk -F'[^[:alnum:]]' '{print $0}' | sort | awk '{ORS=","} {print $0} END{print "\n"}'

